### ISSUE TITLE
This doesn't work for more than 33 person.

### ISSUE THREAD

**Issue by atiabjobayer** [FigBug/Multiplayer-ELO#11]
If you run it with people more than 33, all the rating changes comes 0. it works okay till 33. What's the issue?

I tried the python version.

**Comment by FigBug** [comment]
I think the issue is that ELO changes are always integers, I'm guessing by the time you get to 33 players all the ELO changes are so small that they are less than 0.5 and get rounded to 0.  Remove the round on line 66 and then you can have floating point ELOs. Maybe just round them before displaying to user.
